### ISSUE TITLE
Advice needed about updating and custom rules

### ISSUE THREAD

**Issue by mdlinville** [dita-community/org.dita-community.qa#12]
I'd like to get your updates to how you evaluate exceptions (looks like you put them in an XML structure whereas they used to just be in a string) so I decided to try to update to master today. But then I realized that not only did we add a bunch of rules and remove a bunch of rules, but we also edited the XSL, added a CSV report (I think you might have merged an old version of that, which I should submit a pull request to update), etc. Do you have any best practices anywhere to make the upgrade smoother? This is going to be a pain for me to work through line by line.

And I wish you had not changed the High/Medium/Low to Urgent/Recommended/Low, because that touches a whole lot of stuff that I will have to reconcile by hand. :(

**Comment by bcolborn** [comment]
Was the importance changed? I thought that it was always urgent/recommended/low. Do you know @justdp? The severity maps to @importance, which has these enumerated values: http://docs.oasis-open.org/dita/v1.2/os/spec/common/select-atts.html High/medium/low is allowed so it's not strictly necessary to change them.

My recommendation would be to keep your custom rules in a separate XSLT file that is referenced with xsl:include. Then you can update the base code without touching these rules.

There is also an undocumented stylesheet tools/qacompiler/qa_decompiler.xsl that you can use to convert the xsl:if format to the DITA reference topic format. You can run it outside the plugin (for example, from oXygen). Perhaps that can help with the maintainability.

Truth be told, I struggle with updates as well. Maybe we need an extension point where users can specify their own stylesheets to further separate the base plugin from user rules.

**Comment by justdp** [comment]
I am not certain. If the importance attribute changed, it was several versions back. 

There are a couple of options to reconcile the attributes. The easiest would probably be a search and replace on the _qa_checks XSL file (and any other custom files you have created) to match the current urgent/recommended values. If you've customized the data and report XSL files, then there may some manual adjustments necessary to keep the attributes in sync.   

A second, less-desirable option is to update the qa data XSL and the qa report XSL to specifically look for the attribute values that you're using. However, this would require looking at the logic, changing the count mechanisms for your values, and ensuring that those numbers are expressed accurately in the charts. And you'd run into the same issue at future upgrades.

@bcolborn I think it's worth investigating a better approach for customizing an extension point to the qa checks as well as the final report stylesheets.
