### ISSUE TITLE
If mainbooktitle contains a character such as ™ or ©, the build fails with an XML parser error 

### ISSUE THREAD

**Issue by playaj** [dita-community/org.dita-community.qa#14]
Xerces parser is used by default when running the build.
Full error is
C:\OG43\data\DITA-OT1.8.5\plugins\org.dita.base\build_preprocess.xml:24: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'C:\OG43\temp\9-QA.js186017.248.1490397894340\content\authoring\xlc1485210400966.ditamap'. The XML parser reported the following error: : xlc1485210400966.ditamap Line 14:Invalid byte 1 of 1-byte UTF-8 sequence.
If you change ™ or © to (tm) or (c), the build succeeds.

**Comment by bcolborn** [comment]
This error seems to be at a much lower level than the QA plugin. Can you create HTML output from the map in question? The QA plugin is a customization of HTML output, so if HTML output fails, QA will as well.

**Comment by playaj** [comment]
I am able to generate XHTML and PDF2 output from the same map with no error. 
The log shows that the input file fails at the build_preprocess target.
When I change the ™ or © to (tm) or (c) in the title of the map and generate output for the QA plugin  the build is succeeds.

**Comment by bcolborn** [comment]
I'm not sure about how things are put together at that level. Any insight @justdp or @paqman23?

**Comment by playaj** [comment]
Sorry about the delay. Am attaching log for output of QA plugin with ™ in mainbooktitle.

**Comment by playaj** [comment]
[xlc1485210400966.ot.log.txt](https://github.com/dita-community/org.dita-community.qa/files/884037/xlc1485210400966.ot.log.txt)

**Comment by playaj** [comment]
The fix is relatively easy for this. 
Add encoding="UTF-8" attribute and value for the xmltask.
```
    <xmltask source="${outgen.job.source.filename}" dest="${outgen.job.source.filename}" preservetype="true" encoding="UTF-8">
      <xmlcatalog refid="ot.catalog"/>
      <attr path="/*[contains(@class, ' map/map ')]" attr="chunk" value="to-content"/>
    </xmltask>
```

**Comment by playaj** [comment]
This issue is fixed if you use encoding="UTF-8" attribute and value for the xmltask
