### ISSUE TITLE
Issue with subdirectories in -o parameter

### ISSUE THREAD

**Issue by xavierroy** [dita-community/org.dita-community.qa#4]
The qa plugin does not generate the output html files when you provide a subfolder for the -o parameter.

`dita -f qa -i samples/taskbook.ditamap -Dsetchunk=true` and `dita -f qa -i samples/taskbook.ditamap -o output -Dsetchunk=true`  works without issues.

`dita -f qa -i samples/taskbook.ditamap -o output/qa -Dsetchunk=true` does not work and displays an error. The folder structure is created, but the reports are not generated.

!!! final line of log file
`Error: Fatal error during transformation using D:\dita-ot\plugins\org.dita-community.qa\xsl\qacsv.xsl: java.io.FileNotFoundException: D:\dita-ot\out\plugins\org.oasis-open.dita.v1_2\dtd\technicalContent\dtd\topic.dtd (The system cannot find the path specified)`

**Comment by mdlinville** [comment]
+1

**Comment by justdp** [comment]
Instead of an XSLT task, I've updated the build file to use a java task and explicitly passed the DITA catalog. You can now specify a different output subdirectory.
