### ISSUE TITLE
How to build the <map>-violations.ditamap or <map>.dita?

### ISSUE THREAD

**Issue by mdlinville** [dita-community/org.dita-community.qa#6]
I'm not sure what transform to use for the <map>-violations.ditamap. I have 3 validation errors, but the resulting HTML output is totally blank. The CSV file and .html report outputs shows the violations just fine.

I also tried building the .dita report but it gives a HTML file with text output (no links).

**Comment by mdlinville** [comment]
To follow up, it looks like the href attribute of the violation topicrefs in the generated .ditamap are blank:

```
   <topicref href="">
      <topicmeta>
         <category>
            <keyword>QA violation:</keyword> Found web link that is missing "http://"; Please add. Does not apply to course resources or mailto links.<data name="importance" value="recommended"/>
            <data name="type" value="lang general"/>
         </category>
         <category>
            <keyword>QA violation:</keyword> XREF does not have attribute scope as external<data name="importance" value="urgent"/>
            <data name="type" value="tag general"/>
         </category>
         <category>
            <keyword>QA violation:</keyword> This topic contains at least one instance of passive voice.<data name="importance" value="recommended"/>
            <data name="type" value="lang passive"/>
         </category>
      </topicmeta>
   </topicref>
```

Since the topicref has nothing but topicmeta, I'm not sure how it is supposed to be rendered if I try to build HTML out of the ditamap.

**Comment by bcolborn** [comment]
The @href should definitely be filled with the path of the topic. This is how my output looks.

``` xml
   <topicref href="/Users/Ben%20Colborn/documentation/topics/appliance/cvm_access_c.dita">
      <topicmeta>
         <category>
            <keyword>QA violation:</keyword> This topic contains at least one instance of passive voice.<data name="importance" value="recommended"/>
            <data name="type" value="lang passive"/>
         </category>
      </topicmeta>
   </topicref>
```

The HTML and CSV are generated from the DITA file, so if the paths are in the CSV they must be in the DITA. Then if they are in the DITA, they should be in the map as well.

Can you send me .dita output file?

**Comment by mdlinville** [comment]
Sure, but I'd rather send it to you privately than attach it here. Can you email me at misty at apache org and I'll reply from there.

Also I am running tests now using the pristine plugin, as I had tweaked some of the QA checks and might have screwed something up.

Does it matter that I am on OSX and the script will ultimately be run on a Jenkins host running Linux? I saw that some of the path-changing XSL stuff seems to assume Windows.

**Comment by bcolborn** [comment]
Yes, I'll contact you privately. It's possible that some of the processing for Windows paths could be the culprit, but I'd expect that the @href would in the worst case be mangled, not missing. Anyway, let's see what I can do with the DITA file.

**Comment by mdlinville** [comment]
There are differences in the qacsv.xsl and qadata.xsl and the way they generate the file paths:

_qamap.xsl_

```
        <topicref>
          <xsl:attribute name="href">
            <xsl:value-of
              select="replace(replace(substring-after(current-grouping-key(), 'C:'), '\\', '/'), ' ', '%20')"
             />
          </xsl:attribute>
```

_qacsv.xsl_

```
<xsl:value-of select="concat('=HYPERLINK(&quot;', preceding::data[contains(@name, 'filePath')][1], '&quot;,&quot;', preceding::data[contains(@name, 'topicTitle')][1]/normalize-space(replace(.,',',';')), ' [click to open]&quot;)')"/>
```

From that, it looks like the qamap.xsl could have something like this:

```
        <topicref>
          <xsl:attribute name="href">
            <xsl:value-of
              select="&quot;@name, 'filePath'&quot;"
             />
          </xsl:attribute>
```

I confess to not knowing XSL very much but I will play around and see what I come up with.

**Comment by mdlinville** [comment]
I'm making progress. I have gotten the href of the topicref to have the full path to the file where the error occurs. But if I leave the full path as an absolute path, I get this error:

```
[DOTJ012F] Failed to parse the input file '/Users/misty/tools/DITA-OT/qa_report/director.dita'. The XML parser reported the following error: : null
```

If I make it an absolute path like `../../../director-docs/topics/director_intro.xml` it works but actually pulls in the CONTENT from the file, instead of just pointing to it. I suppose that's expected because that's what a topicref does. But what is it actually supposed to do? Can you send me an example output of transforming the -violations.ditamap and/or the .dita file? What transform are you using?

**Comment by bcolborn** [comment]
I think you're correct about the difference in handling the @href in the two XSLT files. Using substring-after this way was an ill-advised choice that probably would break cross-platform compatibility.

The behavior you are seeing now is expected. If you create output (e.g., PDF or HTML) of the DITAMAP, it would produce the content of all the topics, because as you noted that's what a DITAMAP does. The original idea was that you could open the DITAMAP in your editor to have references to the topics that need attention. It's just a different representation of what is in the CSV file.

**Comment by drmacro** [comment]
The org.dita-community.common.xslt plugin provides the relpath_utils.xsl module that provides functions for working with URLs and for converting to and from Windows-specific paths.

**Comment by mdlinville** [comment]
Thanks @bcolborn. I think we are good for now. I had hoped that the HTML report would be a listing of errors per file, with maybe a link to the offending file (but now that I think about it, I don't know how that would work). Our maps are massive and have way too many topics to be built like this. I'll have a think about it and maybe submit a pull request with a more actionable HTML report. For now, I think the CSV is what we want.

By the way, I yanked out the 'external reference' template and warnings locally because we don't have any prohibition about them. It would be a lot more useful if the script somehow checked them to see if they are broken links, but I'm not sure XSLT can do that. Right now we use xmllint for that.

It might be useful to make some of these tests modular via ant arguments.

**Comment by drmacro** [comment]
With XSLT you can attempt to resolve any URL but if the result isn't parseable as XML it might kill the XSLT process. So probably best to delegate external URL checking to Java code.

**Comment by bcolborn** [comment]
@mstanleyjones it would be straightforward to do what you're talking about. The logic would be very similar to the DITAMAP conversion. Instead of placing the reference to the topic and a list of the violations for that topic into a DITAMAP you could place them into a DITA topic. Then you could output that topic to HTML using the standard OT transformation.

Regarding the external references template, I also don't use it in my environment. Checking that the link is valid would be a nice capability.

**Comment by mdlinville** [comment]
OK, so what we actually wanted was to have the CSV information also show up at the bottom of the -report.html file. Here is how I did it, in case you'd like to include it in a variant template for people who want something more unified.

```
      <div style="padding:10px">
        <h2>Violation Details</h2>
        <table border="1" id="details">
          <thead>
            <tr>
              <td width="20%" nowrap="nowrap"><b>Title</b></td>
              <td width="25%"><b>File Path</b></td>
              <td width="25%"><b>Violation</b></td>
              <td width="10%"><b>Severity</b></td>
              <td width="10%"><b>Type</b></td>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="/topic/body/section[contains(@outputclass, 'to
picReport')]">
              <xsl:for-each select="data/descendant-or-self::*[contains(@type, '
msg')][not(contains(@outputclass, 'step'))][not(contains(@outputclass, 'xrefs'))
]">
                <xsl:choose>
                  <xsl:when test="@importance = 'urgent'">
                    <tr bgcolor="#FFC1C1">
                      <td><xsl:value-of select="preceding::data[contains(@name,
'topicTitle')][1]/normalize-space(replace(.,',',';'))"/></td>
                      <td><tt><xsl:value-of select="preceding::data[contains(@name, 'filePath')][1]"/></tt></td>
                      <td><xsl:value-of select="replace(normalize-space(.), ',',';')"/></td>
                      <td><xsl:value-of select="@importance"/></td>
                      <td><xsl:value-of select="replace(@outputclass,',',';')"/></td>
                    </tr>
                  </xsl:when>
                  <xsl:when test="@importance = 'recommended'">
                    <tr bgcolor="#FFFF99">
                      <td><xsl:value-of select="preceding::data[contains(@name, 'topicTitle')][1]/normalize-space(replace(.,',',';'))"/></td>
                      <td><tt><xsl:value-of select="preceding::data[contains(@name, 'filePath')][1]"/></tt></td>
                      <td><xsl:value-of select="replace(normalize-space(.), ',',';')"/></td>
                      <td><xsl:value-of select="@importance"/></td>
                      <td><xsl:value-of select="replace(@outputclass,',',';')"/></td>
                    </tr>
                  </xsl:when>
                  <xsl:otherwise>
                    <tr>
                      <td><xsl:value-of select="preceding::data[contains(@name, 'topicTitle')][1]/normalize-space(replace(.,',',';'))"/></td>
                      <td><tt><xsl:value-of select="preceding::data[contains(@name, 'filePath')][1]"/></tt></td>
                      <td><xsl:value-of select="replace(normalize-space(.), ',',';')"/></td>
                      <td><xsl:value-of select="@importance"/></td>
                      <td><xsl:value-of select="replace(@outputclass,',',';')"/></td>
                    </tr>
                  </xsl:otherwise>
                </xsl:choose>
              </xsl:for-each>
            </xsl:for-each>
          </tbody>
        </table>
      </div>
```

Urgent errors have a pink background and recommended ones have a yellow background. I had to duplicate the &lt;td&gt; elements because otherwise, XSLT gets confused about where the closing &lt;/tr&gt; is.
